### ISSUE TITLE
Function.php issue

### ISSUE THREAD

**Issue by ghost** [aviraccoon/steam-group-keys#1]
After my first install I tried to run after following your readme

I got an error at Function.php Line 20?

I know this project is 5 years old but any help would be great :D

**Comment by ghost** [comment]
Fatal error: Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/giveaway/inc/functions.php:20 Stack trace: #0 /var/www/html/giveaway/index.php(16): memberlist_save('http://steamcom...', 'inc/memberlist....', Object(SteamAPI)) #1 {main} thrown in /var/www/html/giveaway/inc/functions.php on line 20

**Comment by aviraccoon** [comment]
Install `php7.1-xml` (or other depending on your PHP version) with your package manager.

**Comment by ForgottenSpecialist** [comment]
Hey thanks for the reply, I know get this?

Warning: file_put_contents(inc/memberlist.json): failed to open stream: Permission denied in /var/www/html/giveaway/inc/functions.php on line 50

Fatal error: Uncaught SmartyException: unable to write file ./templates_c/wrt59af3d61597c23.41486303 in /var/www/html/giveaway/inc/smarty/sysplugins/smarty_internal_write_file.php:44 Stack trace: #0 /var/www/html/giveaway/inc/smarty/sysplugins/smarty_internal_template.php(201): Smarty_Internal_Write_File::writeFile('./templates_c/f...', '<?php /* Smarty...', Object(Smarty)) #1 /var/www/html/giveaway/inc/smarty/sysplugins/smarty_internal_templatebase.php(155): Smarty_Internal_Template->compileTemplateSource() #2 /var/www/html/giveaway/inc/smarty/sysplugins/smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('login.tpl', NULL, NULL, Object(Smarty), true) #3 /var/www/html/giveaway/index.php(74): Smarty_Internal_TemplateBase->display('login.tpl') #4 {main} thrown in /var/www/html/giveaway/inc/smarty/sysplugins/smarty_internal_write_file.php on line 44

**Comment by ForgottenSpecialist** [comment]
Permission has been granted to all files.
